calificaciones/urls.py
from django.contrib.auth.decorators import permission_required
from django.urls import path

from . import views
from .views import CalificacionDetailView, CalificacionCreate, CalificacionUpdate, \
    CalificacionDelete, CalificacionAlumnoList, CalificacionDocenteList

calificaciones_patterns = ([
                               # Id de materia, le cargará la lista de notas en esa materia
                               path('<int:id_materia>/', CalificacionAlumnoList.as_view(), name='index_alumno'),

                               path('<int:id_materia>/<int:id_alumno>/', CalificacionDocenteList.as_view(),
                                    name='index_docente'),
                               path('create/<int:id_materia>/<int:id_alumno>/', CalificacionCreate.as_view(),
                                    name='create'),
                               path('update/<int:pk>/', CalificacionUpdate.as_view(), name='update'),
                               path('delete/<int:pk>/', CalificacionDelete.as_view(), name='delete'),

                           ], 'calificacion')

gestornotas/urls.py
from django.contrib import admin
from django.urls import path, include

from calificaciones.urls import calificaciones_patterns
from core.views import index as core_index
from materias.urls import materia_patterns

urlpatterns = [
    path('', core_index, name='index'),
    path('materias/', include(materia_patterns), name='materia'),
    path('calificaciones/', include(calificaciones_patterns), name='calificacion'),

    path('admin/', admin.site.urls),

    # Path de auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),

]

materias/urls.py
from django.contrib.auth.decorators import permission_required
from django.urls import path

from materias.views import MateriaListView, MateriaDetailView, MateriaCreate, MateriaUpdate, MateriaDelete

materia_patterns = ([
                        path('', MateriaListView.as_view(), name='index'),
                        path('<int:pk>/', MateriaDetailView.as_view(), name='materia'),
                        path('create/', permission_required('is_staff')(MateriaCreate.as_view()), name='create'),
                        path('update/<int:pk>/', permission_required('is_staff')(MateriaUpdate.as_view()),
                             name='update'),
                        path('delete/<int:pk>/', permission_required('is_staff')(MateriaDelete.as_view()),
                             name='delete'),
                    ], 'materia')

calificaciones/models.py
from django.contrib.auth.models import User
from django.db import models

from materias.models import Materia


class Calificacion(models.Model):
    TIPO_CALIFICACION = (
        ('Primer parcial', '1er Parcial'),
        ('Segundo parcial', '2do Parcial'),
        ('Exámen final', 'Ex. Final'),
        ('Control', 'Control'),
        ('Prácticos', 'Prácticos'),
    )
    materia = models.ForeignKey(Materia, on_delete=models.CASCADE, blank=True)
    nota = models.DecimalField(max_digits=4, decimal_places=1)
    alumno = models.ForeignKey(User, on_delete=models.CASCADE)
    tipo = models.CharField(choices=TIPO_CALIFICACION, default='Primer Parcial', max_length=100)

    def __str__(self):
        return self.alumno.last_name + ' ' + self.alumno.first_name + ' - ' + self.materia.nombre + ': ' + self.tipo

calificaciones/forms.py
from django import forms

from calificaciones.models import Calificacion


class CalificacionForm(forms.ModelForm):
    materia = forms.TextInput(attrs={'class': 'form-control', })
    alumno = forms.TextInput(attrs={'class': 'form-control', })
    nota = forms.DecimalField(decimal_places=1, max_digits=4, initial=00.0, max_value=100, min_value=0,
                              widget=forms.NumberInput(attrs={
                                  'class': 'form-control',
                              }))
    tipo = forms.ChoiceField(choices=Calificacion.TIPO_CALIFICACION, widget=forms.Select(attrs={
        'class': 'form-control'
    }))

    class Meta:
        model = Calificacion
        fields = ['nota', 'tipo', ]
        labels = {
            'materia': 'Materia',
            'alumno': 'Alumno'
        }

calificaciones/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponse, Http404

from materias.models import Materia
from .forms import CalificacionForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from calificaciones.models import Calificacion


@method_decorator(login_required, name='dispatch')
class CalificacionAlumnoList(ListView):
    """
        Vista de notas para usuarios con rol Alumno
        El alumno podrá ver la lista de notas que tenga en la materia que está observando
        
        :param id_materia
            Este parámetro lo podemos ver en el archivo urls.py de la app

    """
    model = Calificacion
    # El template es calificacion_list_estudiantes (template para vista de estudiantes
    template_name_suffix = '_list_estudiantes'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CalificacionAlumnoList, self).get_context_data(**kwargs)
        # Buscamos si existe una materia con el id pasado por parámetro
        materia = Materia.objects.get(id=self.kwargs['id_materia'])
        if not materia:
            raise Http404
        else:
            # Añadimos al contexto el objeto de la materia
            context['materia'] = materia
        return context

    def get_queryset(self):
        # Calificaciones de ese alumno en la materia pasada por parámetro
        return Calificacion.objects.filter(alumno__calificacion__materia_id=self.kwargs['id_materia']).filter(
            alumno_id=self.request.user.id).distinct()


@method_decorator(login_required, name='dispatch')
class CalificacionDocenteList(ListView):
    """
            Vista de notas para usuarios con rol Docente
            El docente podrá ver la lista de notas que tenga el alumno en la materia

            :param id_materia
            :param id_alumno
                Estos parámetros los podemos ver en el archivo urls.py de la app

        """
    template_name_suffix = '_list_docente'

    def dispatch(self, request, *args, **kwargs):
        # Si el usuario no tiene rol de Docente no puede acceder a la ruta
        if not self.request.user.groups.filter(name='Docente').exists():
            raise Http404
        return super(CalificacionDocenteList, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CalificacionDocenteList, self).get_context_data(**kwargs)
        # Buscamos si existe la materia y el alumno con el id pasado por parámetro
        materia = Materia.objects.get(id=self.kwargs['id_materia'])
        alumno = User.objects.get(id=self.kwargs['id_alumno'])

        # Verificamos que el usuario que quiere ingresar a la vista sea el docente de la materia o sea staff de la pág.
        if not materia or not alumno and (
                not materia.docente.id == self.request.user.id or not self.request.user.is_staff):
            raise Http404
        else:
            context['materia'] = materia
            context['alumno'] = alumno
        return context

    def get_queryset(self):
        # Calificaciones de ese alumno (id pasado por parámetro) en la materia dictada por el usuario en sesión
        return Calificacion.objects.filter(alumno_id=self.kwargs['id_alumno']).filter(
            materia__docente_id=self.request.user.id)


@method_decorator(login_required, name='dispatch')
class CalificacionDetailView(DetailView):
    model = Calificacion


@method_decorator(login_required, name='dispatch')
class CalificacionCreate(CreateView):
    """
        Vista de creación de calificación, solo pueden ingresar usuarios con rol Docente
        En la vista no se muestra un input para ingresar la materia ni el alumno, ya que estos
        datos se los envía por URL

        :param id_materia
        :param id_alumno
    """
    model = Calificacion
    form_class = CalificacionForm

    def dispatch(self, request, *args, **kwargs):
        # Verificamos que el usuario tenga rol Docente
        if not self.request.user.groups.filter(name='Docente').exists():
            raise Http404
        return super(CalificacionCreate, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CalificacionCreate, self).get_context_data(**kwargs)
        materia = Materia.objects.get(id=self.kwargs['id_materia'])
        alumno = User.objects.get(id=self.kwargs['id_alumno'])
        context['materia'] = materia
        context['alumno'] = alumno

        # Si el usuario con rol docente no es el docente de la materia retorna 404
        # (Si falla la vista, eliminar la condición, esta se realizó sin realizar pruebas)
        if not self.request.user.id == materia.docente.id:
            raise Http404
        return context

    def form_valid(self, form):
        # Obtenemos el alumno y la materia en la que crearemos la calificación
        form.instance.materia = Materia.objects.get(id=self.kwargs['id_materia'])
        form.instance.alumno = User.objects.get(id=self.kwargs['id_alumno'])
        form.save()
        return super(CalificacionCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('calificacion:index_docente',
                            kwargs={'id_materia': self.kwargs['id_materia'], 'id_alumno': self.kwargs['id_alumno']})


@method_decorator(login_required, name='dispatch')
class CalificacionUpdate(UpdateView):
    model = Calificacion
    form_class = CalificacionForm
    template_name_suffix = '_update_form'

    def dispatch(self, request, *args, **kwargs):
        # Verificamos que el usuario tenga rol Docente
        if not self.request.user.groups.filter(name='Docente').exists():
            raise Http404
        return super(CalificacionUpdate, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        calificacion = Calificacion.objects.get(id=self.kwargs['pk'])
        return reverse_lazy('calificacion:index_docente',
                            kwargs={'id_materia': calificacion.materia.id, 'id_alumno': calificacion.alumno.id})


@method_decorator(login_required, name='dispatch')
class CalificacionDelete(DeleteView):
    model = Calificacion

    def dispatch(self, request, *args, **kwargs):
        # Verificamos que el usuario tenga rol Docente
        if not self.request.user.groups.filter(name='Docente').exists():
            raise Http404
        return super(CalificacionDelete, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        calificacion = Calificacion.objects.get(id=self.kwargs['pk'])
        return reverse_lazy('calificacion:index_docente',
                            kwargs={'id_materia': calificacion.materia.id, 'id_alumno': calificacion.alumno.id})

calificaciones/templates/calificaciones/calificacion_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar Calificación{% endblock %}
{% block content %}
    <main role="main">
        <div class="container">
            <div class="row mt-3">
                <div class="col-md-9 mx-auto">
                    <div>
                        <h1>{{ object.materia.nombre }}</h1>
                        <p>Alumno: <span>{{ object.alumno.last_name }} {{ object.alumno.first_name }}</span></p>
                        <p>Calificación: <span>{{ object.nota }} - {{ object.tipo }}</span></p>
                        <form action="" method="post">{% csrf_token %}
                            <p>¿Estás seguro de que quiere borrar esta calificación?</p>
                            <input class="btn btn-danger btn-block" type="submit" value="Sí, borrar la calificación"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

calificaciones/templates/calificaciones/calificacion_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Detalle Calificación{% endblock %}
{% block content %}
    <main role="main">
        <div class="container">
            <div class="row mt-3">
                <div class="col-md-9 mx-auto">
                    <h2 class="section-heading mb-4">{{ calificacion.materia__nombre }}</h2>
                    <div>
                        <p>Alumno: <span>{{ calificacion.alumno.first_name }} {{ calificacion.alumno.last_name }}</span>
                        </p>
                        <p>Nota: <span>{{ calificacion.nota }} - {{ calificacion.tipo }}</span></p>

                        {% if request.user.id == calificacion.materia.docente.id %}
                            <p>
                                <a href="{% url 'calificacion:update' calificacion.id %}"
                                   class="btn btn-primary">Editar</a>
                                <a href="{% url 'calificacion:delete' calificacion.id %}" class="btn btn-danger">Eliminar</a>
                            </p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

calificaciones/templates/calificaciones/calificacion_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Crear Reunión{% endblock %}
{% block content %}
    <main role="main">
        <div class="container">
            <div class="row mt-3 mb-3">
                <div class="col-md-9 mx-auto">
                    <h2 class="section-heading mb-2">{{ materia.nombre }}</h2>
                    <p class="h5"> Usted está añadiendo una calificación al alumno:
                        <span>{{ alumno.last_name }} {{ alumno.first_name }}</span></p>
                    <div class="text-danger">
                        {% if form.subject.errors %}
                            <ol>
                                {% for error in form.subject.errors %}
                                    <li><strong>{{ error|escape }}</strong></li>
                                {% endfor %}
                            </ol>
                        {% endif %}
                        {% if form.non_fields_errors %}
                            <div class="form-group text-danger">
                                {{ form.non_fields_errors }}
                            </div>
                        {% endif %}
                    </div>
                    <form action="" method="post">{% csrf_token %}
                        {{ form.as_p }}
                        <div class="text-center">
                            <input class="btn btn-primary btn-block" type="submit" value="Crear calificación"/>
                            <br/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

calificaciones/templates/calificaciones/calificacion_list_docente.html
{% extends 'core/base.html' %}

{% block title %}
    {{ materia.nombre|truncatechars:20 }}
{% endblock %}

{% block content %}
    <main role="main">
        <div class="container">
            <div class="row mt-3">
                <div class="col-md-9 mx-auto">
                    <h1 class="section-heading mb-2">{{ materia.nombre }}</h1>
                    <p class="section-heading mb-2">
                        Docente: <span>{{ materia.docente.last_name }} {{ materia.docente.first_name }}</span></p>
                    <p class="section-heading mb-4">Alumno: <span>{{ alumno.last_name }} {{ alumno.first_name }}</span>
                    </p>
                    <div>
                        <div class="d-flex justify-content-between mb-4 mt-4">
                            <h4>Notas</h4>
                            <div class="mt-2">
                                <a href="{% url 'calificacion:create' materia.id alumno.id %}" class="btn-link">Añadir
                                    nueva
                                    calificación</a>
                            </div>
                        </div>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Tipo</th>
                                <th>Nota</th>
                                <th>Opciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for calificacion in calificacion_list %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ calificacion.tipo }}</td>
                                    <td>{{ calificacion.nota }}</td>
                                    <td>
                                        <a class="btn btn-primary"
                                           href="{% url 'calificacion:update' calificacion.id %}">Editar</a>
                                        <a class="btn btn-danger"
                                           href="{% url 'calificacion:delete' calificacion.id %}">Eliminar</a>
                                    </td>
                                </tr>
                            {% endfor %}


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

calificaciones/templates/calificaciones/calificacion_list_estudiantes.html
{% extends 'core/base.html' %}

{% block title %}
    {{ materia.nombre|truncatechars:20 }}
{% endblock %}

{% block content %}
    <main role="main">
        <div class="container">
            <div class="row mt-3">
                <div class="col-md-9 mx-auto">
                    <h1 class="section-heading mb-4">{{ materia.nombre }}</h1>
                    <h3 class="section-heading mb-2">
                        Docente: {{ materia.docente.first_name|default:'Sin docente' }} {{ materia.docente.last_name|default:'asignado' }}</h3>
                    <p>Días: <span>{{ materia.dias }}</span></p>
                    <p>Horario: <span>de {{ materia.hora_inicio }} a {{ materia.hora_fin }}</span></p>
                    <div>
                        <h3>Notas</h3>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Tipo</th>
                                <th>Nota</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for calificacion in calificacion_list %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ calificacion.tipo }}</td>
                                    <td>{{ calificacion.nota }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

calificaciones/templates/calificaciones/calificacion_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Actualizar página{% endblock %}
{% block content %}
    <main role="main">
        <div class="container">
            <div class="row mt-3">
                <div class="col-md-9 mx-auto">
                    <h2 class="section-heading mb-2">{{ calificacion.materia.nombre }}</h2>
                    <p class="h5"> Usted está actualizando una calificación al alumno:
                        <span>{{ calificacion.alumno.last_name }} {{ calificacion.alumno.first_name }}</span></p>
                    <div>
                        {% if 'ok' in request.GET %}
                            <p style="color:green">
                                Calificación editada correctamente
                                {{ calificacion.id }}
                                <a href="{% url 'calificacion:calificacion' calificacion.id %}">Haz clic aquí para ver
                                    los detalles de la calificación</a>
                            </p>
                        {% endif %}
                        <div class="text-danger">
                            {% if form.subject.errors %}
                                <ol>
                                    {% for error in form.subject.errors %}
                                        <li><strong>{{ error|escape }}</strong></li>
                                    {% endfor %}
                                </ol>
                            {% endif %}
                            {% if form.non_fields_errors %}
                                <div class="form-group text-danger">
                                    {{ form.non_fields_errors }}
                                </div>
                            {% endif %}
                        </div>
                        <form action="" method="post">{% csrf_token %}
                            {{ form.as_p }}
                            <input class="btn btn-primary btn-block" type="submit" value="Guardar calificación"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}